# Generated by Django 5.0.6 on 2024-07-16 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='maquinaProductiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_maquina', models.CharField(max_length=50)),
                ('nombre_maquina', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('fabricante', models.TextField()),
                ('capacidad_produccion', models.FloatField()),
                ('potencia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='fallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('tiempo_falla', models.BigIntegerField()),
                ('descripcion', models.TextField()),
                ('gravedad', models.CharField(max_length=50)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquina_fallas', to='monitoreo.maquinaproductiva')),
            ],
        ),
        migrations.CreateModel(
            name='reporte_diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('produccion_total', models.IntegerField()),
                ('produccion_defectuosa', models.FloatField()),
                ('tasa_defectuosa', models.BigIntegerField()),
                ('tiempo_operacion', models.BigIntegerField()),
                ('tiempo_inactividad', models.BigIntegerField()),
                ('calidad', models.FloatField()),
                ('oee', models.FloatField()),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.maquinaproductiva', verbose_name='reporte_maquina')),
            ],
        ),
        migrations.AddField(
            model_name='maquinaproductiva',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operador', to='monitoreo.usuario'),
        ),
    ]
